### ISSUE TITLE
Inertia.js + Vue 3 support?

### ISSUE THREAD

**Issue by entity** [cruip/laravel-tailwindcss-admin-dashboard-template#1]
Hey folks,

A huge thanks for porting this theme to Laravel. I had wanted to utilise it for ages, but due to time constraints (porting it over) I left it.

It is awesome seeing that you guys have migrated it. I was excited when I saw “Jetstream” and “Vue 3” as this is my current stack (via Inertia.js).

However it seems this is using Livewire instead?

https://github.com/cruip/laravel-tailwindcss-admin-dashboard-template#usage

Looking around they are all blade files.

**Comment by pasqualevitiello** [comment]
Good point! We used the Livewire + Blade stack (https://jetstream.laravel.com/2.x/introduction.html#livewire-blade) so I'd say it's Livewire-ready.

**Comment by entity** [comment]
Any chance you guys can add support for the Jetstream + Inertia.js + Vue 3 stack? @pasqualevitiello

**Comment by pasqualevitiello** [comment]
Actually this is a lite version of a [huge template](https://cruip.com/mosaic), and coding a new version in a different stack is pretty time consuming. But we'll definitely consider to work on the Inertia version if we receive more requests like yours.

**Comment by entity** [comment]
Thank you lots! I’ve got the all pass for the Cruip templates. Just refrained from using because it was a pain to port over.

**Comment by pasqualevitiello** [comment]
Cool, many thanks for your support!
