### ISSUE TITLE
Facing issue in installation with commands  

### ISSUE THREAD

**Issue by amit-webkul** [cruip/laravel-tailwindcss-admin-dashboard-template#13]
**Description**

When I was running **php artisan db:seed** and then I checked and found this error, please check the screenshot attached.
Please help me with a detailed solution for the issue, or please provide me with steps to fix this.

![Screenshot from 2024-05-15 15-40-22](https://github.com/cruip/laravel-tailwindcss-admin-dashboard-template/assets/121479029/9cdccce5-e7ad-41c5-ac22-eab9cd691af0)

**Comment by iStoreBox-Dev** [comment]
same issue here

**Comment by zamblas** [comment]
I think it was fixed on [v3.0.0](https://github.com/cruip/laravel-tailwindcss-admin-dashboard-template/commit/a1bfd7beaa829795687e173b91f3973c5e17d8c9#diff-ccad8b4ee6013765c2bc672aa0515f8e99e42949c914cce01e0cb2b4e882775dL20)
