### ISSUE TITLE
Links in the demo

### ISSUE THREAD

**Issue by ugintl** [cruip/laravel-tailwindcss-admin-dashboard-template#3]
It looks good seeing the demo, but when I click any link in the demo, nothing happens. Is it on purpose?

What version of nodejs do I need to build the frontend?

**Comment by pasqualevitiello** [comment]
That's because is a demo :) Latest Node should work.

**Comment by ugintl** [comment]
@pasqualevitiello How do you do that? I mean disabling the links. It is a useful feature.

**Comment by pasqualevitiello** [comment]
You can just avoid setting the href attribute
