### ISSUE TITLE
Is this really Livewire?

### ISSUE THREAD

**Issue by christoferd** [cruip/laravel-tailwindcss-admin-dashboard-template#4]
I'm confused...
Is this really Livewire as mentioned in the repo's tags?
I found this in the Readme "This project was built with Vue 3 and Vite."
Then in the JS code I see it uses Alpine.js
So, is the Readme out of date? Is this now using Alpine.js and Livewire? Or, does it still use Vue3?

**Comment by pasqualevitiello** [comment]
Hi there,

I've just [updated the README](https://github.com/cruip/laravel-tailwindcss-admin-dashboard-template/commit/0ce72932f7c7b3a787f2e00441e52b88e70fc4e1) file to reflect the template specs.

Mosaic also uses AlpineJS, and here is why: https://laravel-livewire.com/docs/2.x/alpine-js
