### ISSUE TITLE
Upgrade Laravel 10 and Livewire

### ISSUE THREAD

**Issue by nomadtechiemike** [cruip/laravel-tailwindcss-admin-dashboard-template#9]
Hi I am trying to upgrade this to Laravel 10, which seems to work fine, however if I try to upgrade jetstream/livewire I get an error  <x-jet-label class does not found,

**Comment by nomadtechiemike** [comment]
Ok I edited the views and removed jet-

**Comment by jalchr** [comment]
@nomadtechiemike 
Hello,
Can you elaborate more. What has changed in Laravel 10 ?

**Comment by manelgavalda** [comment]
Hi @jalchr 
Just added a PR were you can see the changes: #12
